// Generated by https://quicktype.io

export interface Task {
    id:           number;
    name:         string;
    description:  string;
    status:       string;
    creationDate: string;
    dueDate:      string;
}
