// Generated by https://quicktype.io

export interface Task {
    id:           number;
    name:         string;
    description:  string;
    status:       TypeStatus;
    creationDate: string;
    dueDate:      string;
}

type TypeStatus= 'todo'|'doing'|'done'|''
